### ISSUE TITLE
Not outputting to console

### ISSUE THREAD

**Issue by ricardonunesdev** [Xsmael/node-logger#2]
Hi,

Since v0.1.4 that noogger isn't outputting to console.

I've narrowed down the bug to line 203 of index.js where:
`if(typeof outputLevel != 'string' )`
should actually be
`if(typeof outputLevel == 'string' )`

Otherwise maxlevel isn't initialized for strings, and message isn't written to console.

I've updated my version and it works now.
Please fix and update in npm.

Best regards
Ricardo

**Comment by Xsmael** [comment]
Oh nice catch! Alright Thanks for your support! i'll update it asap, 
--EDIT--

i'm rather going to fix it in next release due to npm versioning system, i can't update it within the same version.

**Comment by Xsmael** [comment]
this has been fixed now as of version 0.1.5
