### ISSUE TITLE
Log files are not rotated correctly

### ISSUE THREAD

**Issue by ElectroBuddha** [Xsmael/node-logger#3]
Hi, 
I have noticed issue with daily log files not rotating correctly. I'm using noogger v.0.1.4 (from: https://www.npmjs.com/package/noogger). 

The issue is caused by log filename not being generated dynamically but only once in `init()` function (`opts.filename`).

I've solved the issue by modifying function `controlledFileOutput` and adding line to it:
`var pathToFile = opts.outputPath + opts.fileNamePrefix + now().format(opts.fileNameDateFormat) + opts.fileNameSuffix +".log";`  
and using it for `fs.appendFile()` so that file path is always generated dynamicaly based on the current date.

**Comment by Xsmael** [comment]
Thanks for this!
i solved the issue and updated it on npm @0.1.5

however i used a different approach to not  affect the performance, especially for systems that write logs alot, to avoid computing the filename each time a log has to be written; so the filename will be updated, each time we cross one day.


Cheers!

**Comment by ElectroBuddha** [comment]
Hi, I've just noticed that you have implemented timeout to wait for the end of the day. The problem is that timeout seems to hold strong reference to function whenTheDayEnds() so script execution can't end until timeout is cleared (could be the whole day). For example we can't end the node script when sending process interrupt signal (pressing: ctrl + c).
