### ISSUE TITLE
Nooger object is not released due to long timeout set in whenTheDayEnds()

### ISSUE THREAD

**Issue by ElectroBuddha** [Xsmael/node-logger#4]
Hi, I've just noticed that you have implemented timeout to wait for the end of the day (related to issue #3 ). The problem is that timeout seems to hold strong reference to function whenTheDayEnds() so any script that includes nooger can't finish execution until timeout is cleared (could be the whole day). For example we can't quit the node script when sending process interrupt signal (pressing: ctrl + c).

**Comment by Xsmael** [comment]
This is very strange, because i tested it before publishing it, but for your sake i tested again, and it works. can you please share the code that fails ?
