### ISSUE TITLE
Operation Question

### ISSUE THREAD

**Issue by bratfry** [Xsmael/node-logger#5]
TEST Javascript based on example  (Raspberry Pi - Jessie)  All up to date versions.   Processing with default options works.    If I process with log.init(logparams);  some of the custom options work and other don't.  outputPath is one that works, filenamePrefix does not work.   

This type of processing creates the error. 
var log = require('noogger').init(logparams);
var logparams = {
	consoleOutput:true,
	consoleOutputLevel:7,
	datetimeformat:"DD-MM-YY HH.mm",
	outputPath:"/home/pi/logs/",
	filenameDateFormat:"DDMMYYYY",
	filenamePrefix:"XXXweatherlogs==>"
		 };
log.warning ("this is an emergency");

RESULT 

pi@raspberrypi:~ $ node consolelogB.js

/home/pi/node_modules/noogger/index.js:143
	opts.outputPath = dfault( o.outputPath, opts.outputPath );
	                           ^
TypeError: Cannot read property 'outputPath' of undefined
    at Object.init (/home/pi/node_modules/noogger/index.js:143:29)
    at Object.<anonymous> (/home/pi/consolelogB.js:5:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
pi@raspberrypi:~ $

So what am I doing wrong.   Thanks   Gary

**Comment by Xsmael** [comment]
you need to define the options first.
You are getting this error because you gave the logparams to the funciton before even defining it.
 try this
```

var logparams = {
  consoleOutput: true,
  consoleOutputLevel: 7,
  datetimeformat: "DD-MM-YY HH.mm",
  outputPath: "/home/pi/logs/",
  filenameDateFormat: "DDMMYYYY",
  filenamePrefix: "XXXweatherlogs==>"
};
// now that logparams is defined you can use it to initialise
var log = require('noogger').init(logparams);

log.warning("this is an emergency");
```

**Comment by bratfry** [comment]
Thanks for the reply,  the positioning was half the problem.  I also had some formatting issues with fileNameDateFormat, fileNamePrefix, and dateTimeFormat.  I have been programming since 1967 and these caps in the variables seem to always give me problems.  You would think I would learn.  :)  Everything works fine now.   Thanks again.    Gary

**Comment by singhayushh** [comment]
rip 🌸

**Comment by Xsmael** [comment]
> rip 🌸

@singhayushh  ??
